server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          lhubsso:
            client-id: dw-service-dev
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/lhubsso"  # ← App Login Callback URL
            scope: openid,profile
            provider: lhubsso
        provider:
          lhubsso:
            authorization-uri: https://sc.lhubsg.com/sam/idp/a/lhubstg/oidc/auth
            token-uri: https://sc.lhubsg.com/sam/idp/a/lhubstg/oidc/token
            jwk-set-uri: https://sc.lhubsg.com/sam/idp/a/lhubstg/oidc/.well-known/keys

  application:
    name: security-connect-integration

app:
  security:
    whitelist:
      - /
      - /favicon.ico
      - /login
      - /oauth2/authorization/lhubsso         # App Login URL
      - /login/oauth2/code/lhubsso            # App Login Callback URL
      - /sso/front-channel-logout             # Front-Channel Logout
      - /sso/back-channel-logout              # Back-Channel Logout

logging:
  level:
    org.springframework.security: DEBUG
