spring:
  security:
    oauth2:
      client:
        registration:
          lhubsso:
            client-id: dw-service-dev
            client-authentication-method: private_key_jwt   # ✅ 关键
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/lhubsso"
            scope: openid,profile
            provider: lhubsso

        provider:
          lhubsso:
            authorization-uri: https://sc.lhubsg.com/sam/idp/a/lhubstg/oidc/auth
            token-uri: https://sc.lhubsg.com/sam/idp/a/lhubstg/oidc/token
            jwk-set-uri: https://sc.lhubsg.com/sam/idp/a/lhubstg/oidc/.well-known/keys
logging:
  level:
    org.springframework.security: DEBUG